### ISSUE TITLE
궁금한점-1

### ISSUE THREAD

**Issue by youngdong82** [architrave-dev/frontend#4]
처음으로 코드를 제대로 이해해보려고 읽어봤는데
ImageStack.tsx처럼 재사용성을 생각하시면서 짠 것이 보여서 재밌게 읽었습니다!!

제가 정확히 이해하지 못한 것일 수 있으나
프로젝트 폴더 구조(?)는 뭔가 복잡하게 되어있는 느낌이 있어요!!

- [x] shared, features, entities, widget 폴더의 각 역할이 뭔가요?

- [x] GlobalNavigation.tsx나 carousel.tsx에 반복적인 ui에 반복문을 사용하지 않은 이유가 있나요??

- [x] pages에는 ArtistLanding.tsx 뿐인데 다른 페이지에 필요한 컴포넌트 조각들이 있는걸로 보아
작은 블록들을 만든 다음 조합해서 큰 페이지를 만드는 방향으로 진행하시는 것 같은데 맞으실까요?

**Comment by caffesale** [comment]
우선 질문에 포괄적으로 답하자면 지금 프로젝트에 적용된 아키텍처는 [fsd architecture](https://feature-sliced.design/docs/get-started/overview)입니다. 

자바스크립트는 모듈 기능의 도입이 늦어 자바에 비해 import의 자유도가 높고 코드와 아키텍처 사이의 갭이 큰 편입니다. 때문에 여러 종류의 아키텍처가 난립하는 경향이 있는데, 특히 단순한 아키텍처를 적용할 경우 components와 utils/helper같은 폴더의 크기가 비대화되고 레벨이 다른 컴포넌트가 혼재하는 상황이 자주 발생합니다. 이걸 피하기 위해서 atomic design과 fsd architecture사이에서 고민하다가 처음 적용해보는 fsd를 우선적으로 테스트해보고 있습니다. 

1. shared, features, entities, widget 폴더 구조에는 위계가 있어 높은 계층의 폴더는 아래 계층의 코드를 이용할 수 있지만, 아래 계층의 폴더에서는 위 계층의 폴더를 이용할 수 없습니다. 예를 들어, shared폴더에 담긴 코드는 다른 모든 폴더에서 import해 사용할 수 있지만, features폴더는 widgets폴더의 코드를 import할 수 없습니다. entities폴더의 코드는 다른 어떤 폴더의 코드도 import할 수 없습니다. 그림으로 대신하는 편이 나을 것 같아 추가 링크 첨부합니다.

[fsd 폴더 구조](https://feature-sliced.design/assets/images/visual_schema-e826067f573946613dcdc76e3f585082.jpg)

2. GlobalNavigation과 carousel파일은 우선적으로 ui를 확인하기위해 작성했으며, api가 추가되는대로 model에 코드를 추가하여 반복문으로 대체할 생각입니다.

3. pages폴더에는 최종적으로 page에 관련된 코드만 남을 예정입니다. 동적 ui와 조합된 컴포넌트는 widgets로, 기능 관련 코드는 features로 분리할 예정이나, 처음 적용해보는 구조라서 시행착오를 겪고 있습니다.

**Comment by youngdong82** [comment]
오호... fsd 아키텍처를 적용하셨군요. atomic 이랑 비슷한 느낌이네요

`shared폴더에 담긴 코드는 다른 모든 폴더에서 import해 사용할 수 있지만, features폴더는 widgets폴더의 코드를 import할 수 없습니다. entities폴더의 코드는 다른 어떤 폴더의 코드도 import할 수 없습니다`

=> import 할 수 없는 것이 혹시 개발자 간 컨벤션인가요? 아님 코드 단에서 막혀있나요?

`pages폴더에는 최종적으로 page에 관련된 코드만 남을 예정입니다. 동적 ui와 조합된 컴포넌트는 widgets로, 기능 관련 코드는 features로 분리할 예정이나, 처음 적용해보는 구조라서 시행착오를 겪고 있습니다.`

=> 작은 것을 만들고 그것들을 조합해서 큰 것을 만드는 바텀 업 방식과
큰 것을 만들고 중복되는 작은 것을 쪼개는 탑 다운 방식을 함께 생각해보는 것도 좋을 것 같아요! 제가 느끼기에는 탑다운 방식이 좀 더 목적지향적인 코딩을 도와주는 느낌인 것 같습니다. TDD도 비슷한 개념인 것 같고요~ㅎㅎ

**Comment by caffesale** [comment]
1. 컨벤션입니다. eslint룰로 코드단에서 강제할 수 있는 플러그인이 존재하지만 협업자가 많지 않아 적용하지 않았습니다.

2. 조언 감사합니다. 적용해보겠습니다

**Comment by youngdong82** [comment]
궁금증이 해결되었습니다ㅎㅎ
답변 감사드립니다!!
